### PR TITLE
Lp1836108

### PR DESCRIPTION
**Pull request by narindergupta**

### CODE REVIEW

**Review by ryan-beisner — CHANGES_REQUESTED** [review]
Please see new issue raised @:
https://bugs.launchpad.net/charm-cinder-pure-storage/+bug/1836273

**Comment by gnuoy** [comment]
This LGTM. I see the readme update has been done. Are we ok to land this now?

**Review by gnuoy — APPROVED** [review]

**Review by ryan-beisner — APPROVED** [review]
My readme concerns are addressed, with the exception of course that it still uses a personal ppa.  But, I think there are immediate plans underway to formalize that packaging.  As long as that is the case, +1.

I've not deployed or tested the code changes.  As long as they are validated by another reviewer, +1.

**Comment by gnuoy** [comment]
I have successfully tested this patch

**Pull request merged**
